<!DOCTYPE html>
<html>
<!-- show list of equipment -->


<head>

    <title>Check Request</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />



    <?php echo $this->getContent(); ?>

</head>


<!-- ------------------------------------------------------------------ -->


<body>

    <div id="fh5co-page">
        <div id="fh5co-main">
            <div class="fh5co-narrow-content">
                <h1 class="fh5co-heading-colored" data-animate-effect="fadeInLeft"> <strong>Check Request</strong></h1>

                <br>

                <div class="row row-bottom-padded-md">
                    <div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
                        <!-- <div class="col-md-3 col-sm-6 col-padding animate-box" data-animate-effect="fadeInLeft"> -->
                        <div class="fh5co-icon"> <i class="icon-search4"></i> </div>
                        <br>
                        <div class="fh5co-text">
                            <input type="text" class="form-control" id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item." id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item.">
                        </div>
                    </div>
                </div>

                <!-- --------------------------------------------------- -->

                <script>
                $(document).ready(function() {
                    $("#myInput").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTable tr").filter(function() {
                            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                    });
                });
                </script>
                <?php echo $this->flashSession->output(); ?>

                <!-- --------------------------------------------------- -->
    
         <h2 class="fh5co-heading">
         <div class="form-gruop">
         <a class="btn btn-primary btn-md" href="<?php echo $this->url->getBaseUri(); ?>checkrequest"
          role="button"> All Request </a>
         <a class="btn btn-primary btn-md" href="<?php echo $this->url->getBaseUri(); ?>checkrequest/wait"
          role="button"> Wait Request </a>
          <a class="btn btn-primary btn-md" href="<?php echo $this->url->getBaseUri(); ?>checkrequest/ready"
          role="button"> Ready Request </a>
          <a class="btn btn-primary btn-md" href="<?php echo $this->url->getBaseUri(); ?>checkrequest/recive"
          role="button"> receive Request </a>
         </div>
         </h2>
                <!-- --------------------------------------------------- -->


                <!------------- equipments list table --------------------------->
                <!-- tr = row = ᡹ x , column = ᡹ y, th = header, td = cell -->
                
                    <table id="myTable" class="table">
                        <tr>
                            <h2 class="fh5co-heading">Check Request</h2>
                        </tr>

                        <thead>
                            <tr>
                                <th data-field="eqname">Request ID</th>
                                <th data-field="eqname">Lend Date</th>
                                <th data-field="eqnum">Student ID</th>
                                <th data-field="eqnum">Status</th>
                                <th data-field="lendnum">Change Status</th>
                            </tr>
                        </thead>
                        <!-- list column 1----------------- -->

                        <?php  
              foreach($sentrq as $row){
              if($row->status == 'receive'){ ?>
                        <form action="checkrequest/save" method="post">
                        <tr>
                            <td>
                                <input type="hidden" id="rqid" name="rqid" value="<?php echo $row->request_id?>">
                                <p class="fh5co-lead"><?php echo $row->request_id ?></p>
                            </td>
                            <td>
                                <p class="fh5co-lead"><?php echo $row->Request_date ?></p>
                            </td>
                            <td>
                                <p class="fh5co-lead"><?php echo $row->Student_id ?></p>
                            </td>
                            <td>
                                <p class="fh5co-lead"><?php echo $row->status ?></p>
                            </td>
                                          <tr>
              <th><h2 class="fh5co-heading" >Equip Name</h2></th>
              <th><h2 class="fh5co-heading"> Quantity </h2></th> 
              </tr>
              <?php
              $requestdetail = request_detail::find("Request_id ='$row->request_id'");
              foreach($requestdetail as $detail){
              $equip = equip::findFirst("Equip_id = '$detail->Equip_id'");
              ?>
            <tr>

              <td>
              <p class="fh5co-lead"><?php echo $equip->Equip_Name ?></p>
              </td>


              <td>
              <p class="fh5co-lead"><?php echo $detail->Equip_Num ?></p></td>
              </tr>
              
              <?php } ?>

            </tr>

          <td>
          <select type="text" name="status" class="about__subtitle" id="status">
          <option value="<?php echo $row->status ?>" 
                  selected="<?php echo $row->status ?>">current status
             - <?php echo $row->status ?></option>
             <option value="1">Wait</option>
             <option value="2">Ready</option>
             <option value="3">receive</option>
            </select>
            </td>
            <td><input class="btn btn-default center-block" type="submit" value="save"></td>
          <td><a href="<?php echo $this->url->getBaseUri().'checkrequest/delete?rqid='.$row->request_id?>">
                      DELETE </a></td>
                        </tr>
                </form>
                <?php } ?>
                <?php } ?>


                <!------------------------- end column 1 -->

                </table>

            </div>
            <!-- </div> -->
        </div>



    </div>





    </div>




    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>

</body>

</html>