<!DOCTYPE html>
<html>

<head>

    <title>Check Request</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />

    <style>
    table,
    td,
    th {
        border: 1px solid #ddd;
        text-align: left;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th,
    td {
        padding: 15px;
    }
    </style>



    <?php echo $this->getContent(); ?>

</head>


<!-- ------------------------------------------------------------------ -->


<body>
    <div id="fh5co-page">
        <div id="fh5co-main">
            <div class="fh5co-narrow-content">

                <h1 class="fh5co-heading-colored" data-animate-effect="fadeInLeft"> <strong>Check Request</strong> : Received Request</h1>

                <br>

                <div class="row row-bottom-padded-md">

                    <div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
                        <!-- <div class="col-md-3 col-sm-6 col-padding animate-box" data-animate-effect="fadeInLeft"> -->
                        <div class="fh5co-icon"> <i class="icon-search4"></i> </div>
                        <br>
                        <div class="fh5co-text">
                            <input type="text" class="form-control" id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item." id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item.">
                        </div>
                    </div>
                </div>

                <!-- --------------------------------------------------- -->

                <script>
                $(document).ready(function() {
                    $("#myInput").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTable tr").filter(function() {
                            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                    });
                });
                </script>
                <?php echo $this->flashSession->output(); ?>

                <!-- --------------------------------------------------- -->

                <div class="animate-box text-center" data-animate-effect="fadeInLeft">
                    <h2 class="fh5co-heading">
                        <div class="form-gruop">
                            <a class="btn btn-primary btn-md" href="<?php echo $this->url->getBaseUri(); ?>checkrequest"
                                role="button">
                                All Request
                            </a>
                            <a class="btn btn-primary btn-md"
                                href="<?php echo $this->url->getBaseUri(); ?>checkrequest/wait" role="button">
                                Wait Request
                            </a>
                            <a class="btn btn-primary btn-md"
                                href="<?php echo $this->url->getBaseUri(); ?>checkrequest/ready" role="button">
                                Ready Request
                            </a>
                            <a class="btn btn-primary btn-md"
                                href="<?php echo $this->url->getBaseUri(); ?>checkrequest/receive" role="button">
                                receive Request
                            </a>
                        </div>
                    </h2>
                </div>

                <!-- --------------------------------------------------- -->


                <!-- left -->
                <?php  
                    foreach($sentrq as $row){
                    if($row->status == 'receive'){ ?>
                <form action="checkrequest/save" method="post">

                    <div class="col-md-5 animate-box" data-animate-effect="fadeInLeft">

                        <h2 class="fh5co-heading"> <strong> Request ID: </strong>
                            <input type="hidden" id="rqid" name="rqid" value="<?php echo $row->request_id?>">
                            <?php echo $row->request_id ?>
                        </h2>

                        <h2 class="fh5co-heading"> <strong> Lending Date: </strong> <?php echo $row->Request_date ?>
                        </h2>
                        <h2 class="fh5co-heading"> <strong> Student ID: </strong> <?php echo $row->Student_id ?> </h2>
                        <h2 class="fh5co-heading"> <strong> Status: </strong> <?php echo $row->status ?> </h2>

                    </div>


                    <!-- right -->
                    <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                        <h2 class="fh5co-heading"> <strong> Detail: </strong></h2>
                        <table>

                            <tr>
                                <th>
                                    <h2 class="fh5co-heading"> Equip Name </h2>
                                </th>
                                <th>
                                    <h2 class="fh5co-heading"> Quantity </h2>
                                </th>
                            </tr>

                            <!-- row2 -->
                            <?php
                                $requestdetail = request_detail::find("Request_id ='$row->request_id'");
                                foreach($requestdetail as $detail){
                                $equip = equip::findFirst("Equip_id = '$detail->Equip_id'");
                            ?>
                            <tr>
                                <td>
                                    <p class="fh5co-lead"><?php echo $equip->Equip_Name ?></p>
                                </td>
                                <td>
                                    <p class="fh5co-lead"><?php echo $detail->Equip_Num ?></p>
                                </td>
                            </tr>

                            <?php } ?>
                        </table>

                        <br><br>

                    </div>

                    <?php } ?>
                    <?php } ?>

                </form>
            </div>

        </div>
    </div>
</body>
</html>