<!DOCTYPE html>
<html>

<!-- show lending history : User Mode -->
<!-- แสดงประวัติการยืม/คืนของนศ รายละเอียดอุปกรณ์ จะต้องกดเข้าไปดูในหน้า detail จะ link กับหน้า history/detail -->


<head>

    <title>Lending History</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />


    <style>
    table,
    td,
    th {
        border: 1px solid #ddd;
        text-align: left;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th,
    td {
        padding: 15px;
    }
    </style>



</head>


<!-- ------------------------------------------------------------------ -->

<body>
    <div id="fh5co-main">
        <form action="request/receive" method="post">
            <div class="fh5co-narrow-content">
                <div class="row row-bottom-padded-md">

                    <h1 class="fh5co-heading-colored"> <Strong> Sent Request </strong></h1>

                    <!-- left -->

                    <?php  
                          foreach($sentstdrq as $row){
                           if($row->status != 'receive')
                        { ?>

                    <br><br><br>

                    <div class="col-md-5 animate-box" data-animate-effect="fadeInLeft">
                        <h2 class="fh5co-heading"> <strong> Request ID: </strong>
                            <input type="hidden" id="rqid" name="rqid" value="<?php echo $row->request_id?>">
                            <?php echo $row->request_id ?>
                        </h2>

                        <h2 class="fh5co-heading"> <strong> Lending Date: </strong> <?php echo $row->Request_date ?>
                        </h2>
                        <h2 class="fh5co-heading"> <strong> Status: <?php echo $row->status ?> </strong> </h2>

                        <?php 
                          if($row->status=='wait'){
                        ?>
                        <a class="btn btn-default"
                            href="<?php echo $this->url->getBaseUri().'request/delete?rqid='.$row->request_id?>">
                            DELETE
                        </a>
                        <?php } ?>

                        <input type="hidden" id="receive" name="receive" value="3">
                        <?php 
                          if($row->status=='ready'){
                        ?>
                        <input class="btn btn-default" type="submit" value="Receive">

                        <br><br>
                        <?php } ?>

                    </div>

                    <!-- -------------------------------------------------- -->

                    <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                        <h2 class="fh5co-heading"> <strong> Detail: </strong></h2>

                        <table>
                            <tr>
                                <th>
                                    <h2 class="fh5co-heading"> Equip Name </h2>
                                </th>
                                <th>
                                    <h2 class="fh5co-heading"> Quantity </h2>
                                </th>
                            </tr>

                            <!-- ----------------------------------------- -->

                            <?php
                          $requestdetail = request_detail::find("Request_id ='$row->request_id'");
                          foreach($requestdetail as $detail){
                            $equip = equip::findFirst("Equip_id = '$detail->Equip_id'");
                        ?>

                            <tr>
                                <!-- equip name -->
                                <td>
                                    <p class="fh5co-lead"> <?php echo $equip->Equip_Name ?> </p>
                                </td>

                                <!-- quatity -->
                                <td>
                                    <p class="fh5co-lead"> <?php echo $detail->Equip_Num ?> </p>
                                </td>
                            </tr>
                            <?php } ?>
                        </table>

                        <br><br>

                    </div>

                    <?php } ?>
                    <?php } ?>
                </div>
            </div>
        </form>
    </div>




    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>

</body>

</html>