<!DOCTYPE html>  
<html>


<head>

<title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">

<link rel="icon" type="image/png" href="public/imag/login/icons/favicon.ico"/>

    <?php echo $this->assets->outputCss('styleslogin'); ?>    
		<?php echo $this->assets->outputJs('scriptslogin'); ?>
		<?php echo $this->assets->outputCss('styles'); ?>    
		<?php echo $this->assets->outputJs('scripts'); ?>  
		<?php echo $this->getContent(); ?>	
			
</head>



<!---------------------------------------------------------------------------------------------------------------->


<body>
<form action="" method="post">

	<div id="fh5co-page">
  <div id="fh5co-main">
		<aside id="fh5co-hero" class="js-fullheight">
			<div class="flexslider js-fullheight">
        <ul class="slides">
          
        <li style="background-image: url(https://cdn.pixabay.com/photo/2016/03/29/16/49/electricity-1288717_1280.jpg);">
				   	<div class="overlay"></div>
				   	<div class="container-fluid">
				   		<div class="row">
					   		<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
					   			<div class="slider-text-inner">
					   				<h1> <strong> Welcome to Lab Lender </strong> </h1>
					   				<h2> Now you can use our web. Please, log in first.</h2>
										<p>
										<a class="btn btn-primary btn-demo popup-vimeo" href="<?php echo $this->url->getBaseUri(); ?>authen/login">Sign In </a> 
                    </p>
					   		  </div>
					   	  </div>
					    </div>
				    </div>
        </li>

    </aside>
</div>

</form>
</body> 
</html>
