<!DOCTYPE html>  
 <html>
 
 <head>

		<title>Member</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
    <link rel="icon" type="image/png" href="public/img/icons/favicon.ico"/>
    
  </head>

 
<!-- หน้านี้กดที่ชื่อ artist แล้วจะ link to artist_detail-->


<div class="container">
<div class="col-lg-8 mx-auto">
<br><br>
          <h2>Member</h2>

          <br><br><br><br><br>

        </div>
      </div>
 
      <head> 
      
      </head>  
      <body>  
           <div class="container container-form">
           <div class="panel panel-primary"> 
                <div class="panel-body">

<br><br>
                     <table data-toggle="table">
                          <thead>
                               <tr>
                               <th data-field="Name">Artist Name</th>
                               <th data-field="Description">Description</th>
                            <th data-field="Style">Style</th>
                            <th data-field="Country">Country</th>
                            <th data-field="DATE_Born">Born</th>
                            
                               </tr>  
                          </thead>  
                          <?php  
                          foreach($sentdata as $row)
                          {   
                          ?>
                               <tr> 
                                    <td> <?php echo $row->name ?> </td>  
                                    <td> <?php echo $row->e_mail ?></td>  
                                    <td> <?php echo $row->Password ?> </td>
                                    <td> <?php echo $row->address ?> </td> 
                                    <td> <?php echo $row->Phone_num ?> </td> 
                               </tr>
                               <?php
                          }  
                          ?>
                     </table> 
                     </div>  
                </div>  
           </div>  



           
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
      </body>  
 </html>  