<!DOCTYPE html>  
<html>


<head>

<title>Login</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">

<link rel="icon" type="image/png" href="public/imag/login/icons/favicon.ico"/>

    <?php echo $this->assets->outputCss('styleslogin'); ?>    
		<?php echo $this->assets->outputJs('scriptslogin'); ?>
		<?php echo $this->assets->outputCss('styles'); ?>    
		<?php echo $this->assets->outputJs('scripts'); ?>  
		<?php echo $this->getContent(); ?>	
			
</head>



<!---------------------------------------------------------------------------------------------------------------->

<body>
<form action="" method="post">

	<div id="fh5co-page">
  <div id="fh5co-main">
		<aside id="fh5co-hero" class="js-fullheight">
			<div class="flexslider js-fullheight">
        <ul class="slides">
          
        <li style="background-image: url(https://cdn.pixabay.com/photo/2016/03/27/20/49/usb-1284227_1280.jpg);">
				   	<div class="overlay"></div>
				   	<div class="container-fluid">
				   		<div class="row">
					   		<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
					   			<div class="slider-text-inner">
					   				<h1> <strong> Please Activate Your Account. </strong> </h1>
					   				<h2> Before you can login, you must active your account with the code sent to your email address.</h2>
										 
									 <div class="container-login100-form-btn m-t-17">
										<button class="login100-form-btn">
										sent email again
										</button>
									</div>
									 
									 </div>
					   	  </div>
					    </div>
				    </div>



        </li>

    </aside>
</div>

</form>
</body> 
</html>
</html>
