
<!DOCTYPE html>  
<html>


 <head>

<title>Join Exhibition</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">



</head>

  <!---------------------------------------------------------------------------------------------------------------->
 
 
 <body>
<div class="container">
<div class="col-lg-8 mx-auto">
<form action="" method="post">
<br><br>
						<!-- page-title -->
						<div class="page-title pb-40">
							<h2 class="page-title__title">Add Art Classroom</h2>
							<p class="page-title__text">Add Classroom Detail</p>
							<div class="page-title__divider"></div>
						</div><!-- End / page-title -->

          <div class="mt-30">
					<h2 class="about__title">Class Name</h2>
                  <input type="text" name="cname" class="about__subtitle" id="cname" required ><br>

                  <h2 class="about__title">Type</h2>
                  <input type="text" name="ctype" class="about__subtitle" id="ctype" required ><br>

                  <h2 class="about__title">Date</h2>
                  <input type="date" name="cdate" class="about__subtitle" id="cdate" required><br>

                  <h2 class="about__title">Tme</h2>
                  <input type="time" name="ctime" class="about__subtitle" id="ctime" required><br>

                  <h2 class="about__title">Artist</h2>
                  <input type="text" name="cartist" class="about__subtitle" id="cartist" required ><br>

                  
                  <br>
                  <br>
                  <br>
                  <br>

          <br>
          <br>
          <br>
          
          <button type="submit" class="md-btn md-btn--outline-primary">Add Classroom</button>
        
          <br>
          <br>
          </form>
          <br>
          <br>


          
          <!-- footer -->
			<div class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-6 col-lg-6 ">
							<p class="footer__coppy">2018 &copy; Copyright <a href="http://awe7.com/">Awe7</a>. All rights Reserved.</p>
						</div>
					</div>
				</div>
			</div><!-- End / footer -->


        
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>

</body>
</html>

