
<!DOCTYPE html>  
<html>

<!-- show lending request : user -->
<!-- แสดงรายการที่ต้องการยืม มีปุ่ม send request สำหรับส่ง request ไปให้ admin/ta -->
<!-- จบหน้านี้อาจจะเด้งไปหน้า history/index -->


<head>

  <title>Lended</title>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />
    

  <?php echo $this->getContent(); ?> 

</head>


<!-- ------------------------------------------------------------------ -->
  

<body>
<div id="fh5co-page">
  <div id="fh5co-main">
    <div class="fh5co-narrow-content">
      <h2 class="fh5co-heading animate-box" data-animate-effect="fadeInLeft" > Equipments that you want to lend</h2>
      <div class="row row-bottom-padded-md">
        <div class="col-md-3 col-sm-6 col-padding animate-box" data-animate-effect="fadeInLeft">
          <div class="blog-entry">
            

          <!------------- equipments list table --------------------------->
          <!-- tr = row = แกน x , column = แกน y, th = header, td = cell -->

          <table class="table">
            <tr>
            <th><h2 class="fh5co-heading" >Equipment Name</h2></th>
            <th><h2 class="fh5co-heading" >Amount</h2></th>
            <th><h2 class="fh5co-heading" >Date/Time</h2></th>
            </tr>

            <!-- list column 1 name----------------- -->

            <tr>

              <!-- equip neme -->
              <td><p>name</p></td>

              <!-- amount -->
              <td><p>amount</p></td>

              <!-- lend date -->
              <td><p> DD/MM/YY 00.00 </p></td>

            </tr>
          </table>

          <br><br><br><br><br>


          <!-- ปุ่ม 2 แบบ จะใช้อันไหนก็แล้วแต่  -->

          <!-- 1 -->
          <button class="btn btn-primary btn-md"> Send Lending Request </button>

          <!-- 2 -->
          <p><a href="#" class="btn btn-primary">Send Lending Request</a></p>


          <!-- status หลังจากกดส่งไปแล้ว ต้องเปลี่ยนเป็น Wait -->
          <h2 class="fh5co-heading"> Status: </h2>

          <!-- update status ตรงนี้ -->
          <h2 class="fh5co-heading"> ------------- </h2>
          

          <!-- ขึ้นหลังจากที่กดปุ่ม send request ไปแล้ว -->
          <p>For recieving your equipment, please wait until status change to READY.</p>

    
          </div>
        </div>
      </div>


    </div>
  </div>

</div>



     
<br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
     <br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
     <br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
  <br><br><br><br><br><br><br><br>

</body>  
 </html>  