<!DOCTYPE html>
<html>
<!-- show list of equipment -->


<head>

    <title>Equipment List</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />



    <?php echo $this->getContent(); ?>

</head>


<!-- ------------------------------------------------------------------ -->


<body>

    <div id="fh5co-page">
        <div id="fh5co-main">
            <div class="fh5co-narrow-content">
                <h1 class="fh5co-heading-colored" data-animate-effect="fadeInLeft"> <strong>Lent</strong></h1>

                <br>

                <div class="row row-bottom-padded-md">
                    <div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
                        <!-- <div class="col-md-3 col-sm-6 col-padding animate-box" data-animate-effect="fadeInLeft"> -->
                        <div class="fh5co-icon"> <i class="icon-search4"></i> </div>
                        <br>
                        <div class="fh5co-text">
                            <input type="text" class="form-control" id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item." id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item.">
                        </div>
                    </div>
                </div>

                <!-- --------------------------------------------------- -->

                <script>
                $(document).ready(function() {
                    $("#myInput").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTable tr").filter(function() {
                            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                    });
                });
                </script>
                <?php echo $this->flashSession->output(); ?>

                <!-- --------------------------------------------------- -->


                <!------------- equipments list table --------------------------->
                <!-- tr = row = แกน x , column = แกน y, th = header, td = cell -->
                    <table id="myTable" class="table">
                    
                        <tr>
                            <h2 class="fh5co-heading">Equipment Name</h2>
                        </tr>
                        <thead>
                            <tr>

                                <th data-field="eqname">Equip ID</th>
                                <th data-field="eqname">Equip Name</th>
                                <th data-field="eqnum">Quantity</th>

                            </tr>
                        </thead>
                        <!-- list column 1----------------- -->

                        <?php  
              foreach($lineitems as $row)
            { 
              $equip = $row['equip'];?>
            <form action="lend/request" method="post">
                        <tr>
                            <td>
                                <!-- <p class="fh5co-lead"><?php echo $equip->Equip_id ?></p> -->
                                <input type="hidden" name="equip[]" readonly value="<?php echo $equip->Equip_id?>">
                                <!-- <input type="hidden" name="eqid" id="eqid" value="<?php echo $equip->Equip_id?>"> -->
                            </td>
                            <td>
                                <p class="fh5co-lead"><?php echo $equip->Equip_Name ?></p>
                            </td>
                            <td>
                                <p class="fh5co-lead"><?php echo $row['qty'] ?></p>
                                <input type="hidden" name="eqnum[]" readonly value="<?php echo $row['qty'] ?>">
                                <!-- <input type="hidden" name="eqnum" id="eqnum" value="<?php echo $row['qty'] ?>"> -->
                            <!-- <td>
                            <button type="button" class="btn btn-default" value="remove" onClick="$(this).closest('tr').remove();">Remove</button>
			                </td>
                            <td><a href="<?php echo $this->url->getBaseUri().'lend/delete'?>">
                                    DELETE </a></td> -->
                        </tr>
                <?php } ?>


                <!------------------------- end column 1 -->
                </table>

            </div>
            <!-- </div> -->

            <a href="<?php echo $this->url->getBaseUri().'lend/emptyCart'?>">
                        empty </a>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>



    </div>





    </div>




    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>

</body>

</html>