
<!DOCTYPE html>  
<html>

<!-- show list of request equipment : admin mode -->
<!-- ดูรายละเอียดของที่ user จะยืม แล้วเปลี่ยน status จาก wait เป็น ready เมื่อจัดของเสร็จ -->



<head>

  <title>Request Detail</title>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />
    


  <?php echo $this->getContent(); ?> 

</head>


<!-- ------------------------------------------------------------------ -->
  

<body>

<div id="fh5co-page">
  <div id="fh5co-main">
    <div class="fh5co-narrow-content">
      <h1 class="fh5co-heading-colored" data-animate-effect="fadeInLeft" > <strong>Detail</strong></h1>
     
      <br>



          <!------------- table --------------------------->
          <!-- tr = row = แกน x , column = แกน y, th = header, td = cell -->

			<table id="myTable" class="table">

      <!-- row 1 head -->
      <tr>
        <th><h2 class="fh5co-heading" >Equipment</h2></th>
		<th><h2 class="fh5co-heading"> Amount </h2></th>
        <th><h2 class="fh5co-heading"> Lend Date </h2></th>
		<th><h2 class="fh5co-heading"> Return Date </h2></th>
      </tr>
      <!------------------------ end row 1 -->

      <!-- row 2++ -->
      
      <?php  
        foreach($sentdata as $row)
      { ?>

      <tr>
        <!-- equipment-->
        <td><p class="fh5co-lead"><?php echo $row->EquipName ?></p></td>

        <!-- amount -->
        <td><input type="number" id="myNumber" class="input-group" value="1" min="1"></td>

        <!-- date and time lend -->
        <td><p>DD/MM/YY 00.00</p></td>

		 <!-- date and time return-->
		 <td><p>DD/MM/YY 00.00</p></td>

      </tr>  

      <?php } ?>

      <!------------------------- end row 2++ -->
    </table>

<!-- end table----------------------------------------------------------- -->


 		

		 <!--------------------- change status : admin/ta --------------------->
		<div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
			<div class="slider-text-inner">
				<h1> <strong> Change Status </strong></h1>



				

				<!-- ไม่แน่ใจว่าต้องใช้ปุ่ม recieved มั้ยเพราะจริงๆ แล้วกำหนดให้คนกด recieved คือ user ถ้าไม่ใช่ก็ลบไป -->
				<!-- button 1 ถ้าเละใช้ button 2 -->
				<p>
                    <a class="btn btn-primary btn-demo popup-vimeo"> Ready </a> 
                    <a class="btn btn-primary btn-learn"> Recieved </a>
                </p>


				<!-- button 2 -->
				<button class="btn btn-primary btn-md"> Ready </button>
				<button class="btn btn-primary btn-md"> Recieved </button>
			</div>
		</div>


		 <!-------------------------------------------------------->


          </div>
        <!-- </div> -->
      </div>
    
  </div>


</div>



     
<br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
     <br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
     <br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br>
  <br><br><br><br><br><br><br><br>

</body>  
 </html>  