<!DOCTYPE html>
<html lang="en">


<head>

    <title>Add student</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />

    <?php echo $this->getContent(); ?>

</head>

<!-- ------------------------------------------------------------------ -->


<body>
    <div id="fh5co-page">
        <div id="fh5co-main">
            <div class="fh5co-narrow-content">
                <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
										<br><br><br><br><br><br>
										
								<img class="img-responsive"
                        src="https://cdn.pixabay.com/photo/2017/07/31/11/21/people-2557396_1280.jpg">
                </div>
                <form action="" method="post">

                    <?php echo $this->flashSession->output(); ?>

                    <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
												<h1><strong>Add Member</strong> : Student</h1>
												
												<br><br>

                        <h2 class="fh5co-heading">E-Mail: </h2>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email"
                            required></p>

                        <h2 class="fh5co-heading">Password: </h2>
                        <input type="password" class="form-control" id="psw" name="psw" placeholder="Enter Password"
                            required></p>

                        <h2 class="fh5co-heading">Name: </h2>
                        <input type="text" class="form-control" id="fname" name="fname"
                            placeholder="Enter Your First Name" required></p>

                        <h2 class="fh5co-heading">Phone Number: </h2>
                        <input type="text" class="form-control" id="tel" name="tel"
                            placeholder="Enter Your Phone NUmber" required></p>


												<h2 class="fh5co-heading"> Student ID:</h2>
												<input type="text" class="form-control" id="studentid" name="studentid"
												placeholder="Enter Your student id" required></p>


                        <br><br><br><br><br>

                        <div class="container-login100-form-btn m-t-17">
                            <button class="btn btn-primary btn-md" type="submit">
                                Add Student
														</button>
														
                            <button class="btn btn-primary btn-md" value="Go back!" onclick="history.back()">
                                Back
														</button>
										
                        </div>

                    </div>
                </form>
            </div>


        </div>
    </div>
    </div>



    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>


</body>

</html>