<!DOCTYPE html>
<html>


<head>

    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <link rel="icon" type="image/png" href="public/img/icons/favicon.ico" />

</head>


<!---------------------------------------------------------------------------------------------------------------->


<body>
    <div id="fh5co-page">
        <form action="" method="post">
            <div class="fh5co-main">
               

                        <!-- page-title -->
                        <div class="page-title pb-40">
                            <h2 class="page-title__title">Add Member By Admin</h2>

                            <div class="page-title__divider"></div>
                        </div><!-- End / page-title -->

                    </div>
                </section>
                <!-- End / Section -->


                <!-- Section -->
                <section class="awe-section bg-gray">
                    <div class="container">
                        <div class="row">
                            
                            <div
                                class="col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-1 ">

                                <?php echo $this->flashSession->output(); ?>

                                <!--  -->
                                <form action="" method="post">
                                    <div class="mt-30">
                                        <h2 class="about__title">E-Mail:</h2>
                                        <input type="email" placeholder="Enter Email" name="email"
                                            class="about__subtitle" id="email" required><br>

                                        <h2 class="about__title">Password:</h2>
                                        <input type="password" placeholder="Enter Password" name="psw"
                                            class="about__subtitle" id="psw" required><br>

                                        <h2 class="about__title">Name:</h2>
                                        <input type="text" placeholder="Enter Your First Name" name="fname"
                                            class="about__subtitle" id="fname" required><br>

                                        <h2 class="about__title">Phone Number:</h2>
                                        <input type="text" placeholder="Enter Your Phone NUmber" name="tel"
                                            class="about__subtitle" id="tel" required><br>

                                        <h2 class="about__title">Lab ID:</h2>
                                        <select type="text" name="labid" class="about__subtitle" id="labid">
                                            <?php foreach($sentlab as $row){ ?>
                                            <option value="<?php echo $row->Lab_id?>"><?php echo $row->Lab_id?> -
                                                <?php echo $row->Class_Name?> </option>
                                            <?php } ?>
                                        </select>
                                        <!-- <input type="text" placeholder="Enter Your Lab id" name="labid" class="about__subtitle" id="labid" required ><br> -->

                                        <br>
                                        <br>
                                        <br>
                                        <br>

                                        <div class="container-login100-form-btn m-t-32">
                                            <button class="login100-form-btn" type="submit">
                                                Add TA
                                            </button>
                                        </div>

                                        <div class="container-login100-form-btn m-t-32">
                                            <button class="login100-form-btn" value="Go back!" onclick="history.back()">
                                                Back
                                            </button>
                                        </div>

                                </form>
                            </div>


                        </div><!-- End /  -->

                    </div>
            </div>
    </div>
    </section>


    </div>


    </form>
    </div>


    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>

</body>
</html>