<!DOCTYPE html>  
<html>


<head>

<title>Home</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">

s
    <?php echo $this->assets->outputCss('styleslogin'); ?>    
    <?php echo $this->assets->outputJs('scriptslogin'); ?> 

    <link rel="icon" type="image/png" href="public/img/icons/favicon.ico"/>

</head>


<!---------------------------------------------------------------------------------------------------------------->


<body>


<div class="page-wrap" id="root">
  <form action="" method="post">			
   
			<!-- Content-->
			<div class="wil-content">
				
				<!-- Section -->
				<section class="awe-section">
					<div class="container">
						
						<!-- page-title -->
						<div class="page-title pb-40">
							<h2 class="page-title__title">Edit External Collection</h2>

							<div class="page-title__divider"></div>
						</div><!-- End / page-title -->
						
					</div>
				</section>
				<!-- End / Section -->
				
				
				<!-- Section -->
				<section class="awe-section bg-gray">
					<div class="container">
						<div class="row">
							<div class="col-md-6 col-lg-5 "><img src="https://images.pexels.com/photos/797558/pexels-photo-797558.jpeg?w=1260&amp;h=750&amp;auto=compress&amp;cs=tinysrgb" alt="">
							</div>
							<div class="col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-1 ">
								
								<!--  -->
								<div class="mt-30">

                  <h2 class="about__title">Name</h2>
                  <input type="text" placeholder="External Name" name="exname" class="about__subtitle" id="exname" value="<?php echo $extcol->Name?>" required ><br>

                  <h2 class="about__title">Contact Person</h2>
                  <input type="text" placeholder="Contact Person"  name="excont" class="about__subtitle" id="excont" value="<?php echo $extcol->Contact_person?>" required ><br>

                  <h2 class="about__title">Phone</h2>
                  <input type="text" placeholder="Phone" name="exphone" class="about__subtitle" id="exphone" value="<?php echo $extcol->Phone?>" required ><br>

                  <h2 class="about__title">Address</h2>
                  <input type="text" placeholder="Address" name="exaddr" class="about__subtitle" id="exaddr" value="<?php echo $extcol->Address?>" ><br>

                  <h2 class="about__title">Type</h2>
                  <input type="text" placeholder="Type" name="extype" class="about__subtitle" id="extype" value="<?php echo $extcol->Type?>" ><br>

                  <h2 class="about__title">Description</h2>
                  <input type="text" placeholder="Description" name="exdes" class="about__subtitle" id="exdes" value="<?php echo $extcol->Description?>" ><br>

                  <br>
                  <br>
                  <br>
                  <br>

                  <div class="container-login100-form-btn m-t-32">
						        <button class="login100-form-btn" type="submit">
							        Edit External Collection
						        </button>
					        </div>


					        </div>

									
								</div><!-- End /  -->
								
							</div>
						</div>
					</div>
				</section>
				<!-- End / Section -->
	</form>			
			</div>
			<!-- End / Content-->
      
      
      

			<!-- footer -->
			<div class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-6 col-lg-6 ">
							<p class="footer__coppy">2018 &copy; Copyright <a href="http://awe7.com/">Awe7</a>. All rights Reserved.</p>
						</div>
					</div>
				</div>
			</div><!-- End / footer -->
			
    </div>


        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>




</form>

</body>
</html>
