
<!DOCTYPE html>  
<html>

<!-- หน้านี้กดที่ชื่อ artist แล้วจะ link to artist_detail-->

<head>

		<title>Artist</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
	
    <?php echo $this->assets->outputCss('styles'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?> 

    
  </head>
<!------------------------------------------------------------------------------------------------------------------->

<body>


<div class="page-wrap" id="root">

			<!-- Content-->
			<div class="wil-content">

      	<!-- Section -->
				<section class="awe-section">
					<div class="container">
						
						<!-- page-title -->
						<div class="page-title pb-40">
							<h2 class="page-title__title">External Collection</h2>
							<p class="page-title__text">Curabitur elementum urna augue, eu porta</p>
							<div class="page-title__divider"></div>
            </div><!-- End / page-title -->

					
          <br>
          <br>

<div class="container-login100-form-btn m-t-32">
            <a href="<?php echo $this->url->getBaseUri(); ?>collection" class="login100-form-btn" role="button" >Manage Collection</a>
</div>

<div class="container-login100-form-btn m-t-32">
            <a href="<?php echo $this->url->getBaseUri(); ?>collection/addext" class="login100-form-btn" role="button" >Add External Collection</a>
</div>

          
          
          </div>
        </section>
        
				<!-- End / Section -->
    
      
      <!-- อันนี้จะเชื่อมไปหน้า catagory -->
      <!-- <button class="btn">BROWSE BY ARTIST</button> -->

      <br>
      <br>
      <br>
      <br>
      <br>

      </div>
    </div>
        
           <div class="container container-form">
           <div class="panel panel-primary"> 
              <div class="panel-body">

              <br>
              <br>
                     <table data-toggle="table">
                          <thead>
                               <tr>
                               <th data-field="Name">Object Name</th>
                                <th data-field="type">Type</th>
                                <th data-field="addr">Address</th>
                                <th data-field="phone">Phone Number</th>
                                <th data-field="person">Contact Person</th>
                                <th data-field="des">Description</th>
                            
                               </tr>  
                          </thead>  

                          <?php
                          foreach($sentextobj as $row)
                          {
                            //   $aobj=ArtObject::FindFirst("obj_id ='$row->obj_id'");
                          ?>
                               <tr>  
                                      <td> <?php echo $row->Name ?> </td> 
                                      <td> <?php echo $row->Type ?> </td> 
                                      <td> <?php echo $row->Address ?> </td> 
                                      <td> <?php echo $row->Phone ?> </td>
                                      <td> <?php echo $row->Contact_person ?> </td>
                                      <td> <?php echo $row->Description ?> </td>

                                      <td><a href="<?php echo $this->url->getBaseUri().'collection/editext?Name='.$row->Name; ?>" class="btn navbar-btn">Edit</a></td>
                                    <td><a href="<?php echo $this->url->getBaseUri().'collection/deleteext?Name='.$row->Name; ?>" class="btn navbar-btn">Delete</a></td>
                               </tr>
                               <?php
                          }  
                          ?>
                     </table> 
                     </div>  
                </div>  

                
           </div> 

        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>

      </body>  
 </html>  