
<!DOCTYPE html>  
<html>

<!-- หน้านี้กดที่ชื่อ artist แล้วจะ link to artist_detail-->

<head>

		<title>Artist</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
	
    <?php echo $this->assets->outputCss('styles'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?> 

    
  </head>
<!------------------------------------------------------------------------------------------------------------------->

<body>


<div class="page-wrap" id="root">

			<!-- Content-->
			<div class="wil-content">

      	<!-- Section -->
				<section class="awe-section">
					<div class="container">
						
						<!-- page-title -->
						<div class="page-title pb-40">
							<h2 class="page-title__title">Manage Collection</h2>
							<p class="page-title__text">Curabitur elementum urna augue, eu porta</p>
							<div class="page-title__divider"></div>
            </div><!-- End / page-title -->


            <div class="container-login100-form-btn m-t-32">
            <a href="<?php echo $this->url->getBaseUri(); ?>catagory" class="btn" role="button" >CATEGORY</a>
</div>
					
          <br>
          <br>

<div class="container-login100-form-btn m-t-32">
            <a href="<?php echo $this->url->getBaseUri(); ?>collection/permanent" class="btn" role="button" >Permanent Collection</a>
</div>

<div class="container-login100-form-btn m-t-32">
            <a href="<?php echo $this->url->getBaseUri(); ?>collection/external" class="btn" role="button" >External Collection</a>
</div>

<div class="container-login100-form-btn m-t-32">
            <a href="<?php echo $this->url->getBaseUri(); ?>collection/borrowed" class="btn" role="button" >Borrowed Collection</a>
</div>
          
          </div>
        </section>
        
				<!-- End / Section -->
    
      
      <!-- อันนี้จะเชื่อมไปหน้า catagory -->
      <!-- <button class="btn">BROWSE BY ARTIST</button> -->

      <br>
      <br>
      <br>
      <br>
      <br>

      </div>
    </div>
        
    <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>

      </body>  
 </html>  