<!DOCTYPE html>  
<html>
<?php echo $this->flashSession->output(); ?>

<head>

<title>Home</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">

    <?php echo $this->assets->outputCss('styleslogin'); ?>    
    <?php echo $this->assets->outputJs('scriptslogin'); ?> 

    <link rel="icon" type="image/png" href="public/img/icons/favicon.ico"/>

</head>


<!---------------------------------------------------------------------------------------------------------------->


<body>


<div class="page-wrap" id="root">
  <form action="" method="post">			
   
			<!-- Content-->
			<div class="wil-content">
				
				<!-- Section -->
				<section class="awe-section">
					<div class="container">
						
						<!-- page-title -->
						<div class="page-title pb-40">
							<h2 class="page-title__title">Add equip</h2>

							<div class="page-title__divider"></div>
						</div><!-- End / page-title -->
						
					</div>
				</section>
				<!-- End / Section -->
				
				
				<!-- Section -->
				<section class="awe-section bg-gray">
					<div class="container">
						<div class="row">
							<div class="col-md-6 col-lg-5 "><img src="https://images.pexels.com/photos/797558/pexels-photo-797558.jpeg?w=1260&amp;h=750&amp;auto=compress&amp;cs=tinysrgb" alt="">
							</div>
							<div class="col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-1 ">
								
								<!--  -->
								<div class="mt-30">
					<h2 class="about__title">Equip ID</h2>
                  <input type="text" placeholder="Equip Id" name="eqid" class="about__subtitle" id="eqid" required ><br>

                  <h2 class="about__title">Equip Name</h2>
                  <input type="text" placeholder="Equip Name"  name="eqname" class="about__subtitle" id="eqname" required ><br>

                  <h2 class="about__title">Equip Quantity</h2>
                  <input type="text" placeholder="Equip Quantity" name="eqnum" class="about__subtitle" id="eqnum" required ><br>

									<h2 class="about__title">Lab ID</h2>
									<select type="text" name="labid" class="about__subtitle" id="labid">
				  				<?php foreach($sentlab as $row){ ?>
          				<option value="<?php echo $row->Lab_id?>"><?php echo $row->Lab_id?> - <?php echo $row->Class_Name?> </option>
          				<?php } ?>
				  				</select>
                  <!-- <input type="text" placeholder="Lab ID" name="labid" class="about__subtitle" id="labid" required ><br> -->
                  
                  <br>
                  <br>
                  <br>
				  <br>
				  

                  <div class="container-login100-form-btn m-t-32">
						        <button class="login100-form-btn" type="submit">
							        Add Equip
						        </button>
									</div>

									<div class="container-login100-form-btn m-t-32">
						        <button class="login100-form-btn" value="Go back!" onclick="history.back()">
							        Back
						        </button>
					        </div>


					        </div>

									
								</div><!-- End /  -->
								
							</div>
						</div>
					</div>
				</section>
				<!-- End / Section -->
	</form>			
			</div>
			<!-- End / Content-->
      
      
      

		<!-- footer -->
		<div class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-6 col-lg-6 ">
							<p class="footer__coppy">2018 &copy; Copyright <a href="http://awe7.com/">Awe7</a>. All rights Reserved.</p>
						</div>
					</div>
				</div>
			</div><!-- End / footer -->


        
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>



</body>
</html>
