<!DOCTYPE html>  
<html>


<head>

<title>Home</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-capable" content="yes">

s
    <?php echo $this->assets->outputCss('styleslogin'); ?>    
    <?php echo $this->assets->outputJs('scriptslogin'); ?> 

    <link rel="icon" type="image/png" href="public/img/icons/favicon.ico"/>

</head>


<!---------------------------------------------------------------------------------------------------------------->


<body>


<div class="page-wrap" id="root">
  <form action="" method="post">			
   
			<!-- Content-->
			<div class="wil-content">
				
				<!-- Section -->
				<section class="awe-section">
					<div class="container">
						
						<!-- page-title -->
						<div class="page-title pb-40">
							<h2 class="page-title__title">Add Art Object</h2>

							<div class="page-title__divider"></div>
						</div><!-- End / page-title -->
						
					</div>
				</section>
				<!-- End / Section -->
				
				
				<!-- Section -->
				<section class="awe-section bg-gray">
					<div class="container">
						<div class="row">
							<div class="col-md-6 col-lg-5 "><img src="https://images.pexels.com/photos/797558/pexels-photo-797558.jpeg?w=1260&amp;h=750&amp;auto=compress&amp;cs=tinysrgb" alt="">
							</div>
							<div class="col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-1 ">
								
								<!--  -->
								<div class="mt-30">
					<h2 class="about__title">Object Id</h2>
                  <input type="text" placeholder="Object Id" name="objid" class="about__subtitle" id="objid" required ><br>

                  <h2 class="about__title">Art Object Title</h2>
                  <input type="text" placeholder="Art Object Title"  name="atitle" class="about__subtitle" id="atitle" required ><br>

                  <h2 class="about__title">Artist Name</h2>
                  <input type="text" placeholder="Artist Name" name="arname" class="about__subtitle" id="arname" required ><br>

                  <h2 class="about__title">Style</h2>
                  <input type="text" placeholder="Object Style" name="astyle" class="about__subtitle" id="astyle"  ><br>

                  <h2 class="about__title">Origin</h2>
                  <input type="text" placeholder="Object Origin" name="aorigin" class="about__subtitle" id="aorigin"  ><br>

                  <h2 class="about__title">Year</h2>
                  <input type="date" placeholder="Object Year" name="ayear" class="about__subtitle" id="ayear" ><br>

				  <h2 class="about__title">Epoch</h2>
                  <input type="text" placeholder="Object Epoch" name="epoch" class="about__subtitle" id="epoch" ><br>

                  <h2 class="about__title">Description</h2>
                  <input type="text" placeholder="Art Object Description" name="ades" class="about__subtitle" id="ades"  ><br>

				  <h2 class="about__title">Art Type</h2>
                  <select type="text" name="type" class="about__subtitle" id="type">
				  <option value="1" >Painting</option>
    			  <option value="2" >Sculpture</option>
				  <option value="3" >Statue</option>
				  <option value="4" >Other</option>
				  </select>
                  
                  <br>
                  <br>
                  <br>
				  <br>
				  

                  <div class="container-login100-form-btn m-t-32">
						        <button class="login100-form-btn" type="submit">
							        Add Art Object
						        </button>
					</div>


					        </div>

									
								</div><!-- End /  -->
								
							</div>
						</div>
					</div>
				</section>
				<!-- End / Section -->
	</form>			
			</div>
			<!-- End / Content-->
      
      
      

		<!-- footer -->
		<div class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-6 col-lg-6 ">
							<p class="footer__coppy">2018 &copy; Copyright <a href="http://awe7.com/">Awe7</a>. All rights Reserved.</p>
						</div>
					</div>
				</div>
			</div><!-- End / footer -->


        
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
        <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>
			  <br><br><br><br><br><br><br><br>






</form>

</body>
</html>
