<!DOCTYPE html>
<html lang="en">


<head>

    <title>Add Equipment</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />

    <?php echo $this->getContent(); ?>

</head>

<!-- ------------------------------------------------------------------ -->


<body>
    <div id="fh5co-page">
        <div id="fh5co-main">
            <div class="fh5co-narrow-content">
                <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                    <br><br><br><br><br><br>

                    <img class="img-responsive"
                        src="https://cdn.pixabay.com/photo/2016/06/08/05/44/circuit-1443251_1280.jpg">
                </div>
                <form action="" method="post">

                    <?php echo $this->flashSession->output(); ?>

                    <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                        <h1><strong>Edit Equipment</strong></h1>

                        <br><br>

                        <h2 class="fh5co-heading">Equipment ID: <?php echo $sentediteq->Equip_id?> </h2>


                        <h2 class="fh5co-heading">Equipment Name: </h2>
                        <input type="text" class="form-control" id="eqname" name="eqname"
                            value="<?php echo $sentediteq->Equip_Name?>" required></p>

                        <h2 class="fh5co-heading">Equipment Quantity: </h2>
                        <input type="text" class="form-control" id="eqnum" name="eqnum"
                            value="<?php echo $sentediteq->Equip_Num?>" required></p>


                        <h2 class="fh5co-heading">Lab ID</h2>
                        <select type="text" name="labid" class="about__subtitle" id="labid">
                            <?php foreach($sentlab as $row){ ?>
                            <option value="<?php echo $row->Lab_id?>"><?php echo $row->Lab_id?> -
                                <?php echo $row->Class_Name?> </option>
                            <?php } ?>
                        </select>


                        <br><br><br><br><br>

                        <div class="container-login100-form-btn m-t-17">
                            <button class="btn btn-primary btn-md" type="submit">
                                Edit Equipment
                            </button>

                            <button class="btn btn-primary btn-md" value="Go back!" onclick="history.back()">
                                Back
                            </button>

                        </div>

                    </div>
                </form>
            </div>


        </div>
    </div>
    </div>



    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br>


</body>

</html>