<!DOCTYPE html>
<html>
<!-- show list of equipment -->


<head>

    <title>Equipment List</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />



    <?php echo $this->getContent(); ?>

</head>


<!-- ------------------------------------------------------------------ -->


<body>

    <div id="fh5co-page">
        <div id="fh5co-main">
            <div class="fh5co-narrow-content">
                <h1 class="fh5co-heading-colored" data-animate-effect="fadeInLeft"> <strong>Lab Equipment </strong></h1>

                <br>

                <div class="row row-bottom-padded-md">
                    <div class="fh5co-feature animate-box" data-animate-effect="fadeInLeft">
                        <div class="fh5co-icon"> <i class="icon-search4"></i> </div>
                        <br>
                        <div class="fh5co-text">
                            <input type="text" class="form-control" id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item." id="myInput" onkeyup="myFunction()"
                                placeholder="Search for item.">
                        </div>
                    </div>
                </div>

                <!-- --------------------------------------------------- -->

                <script>
                $(document).ready(function() {
                    $("#myInput").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTable tr").filter(function() {
                            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                    });
                });
                </script>
                <?php echo $this->flashSession->output(); ?>

                <!-- --------------------------------------------------- -->
                <?php
            if(!$this->session->has('studentID')){ ?>

                <div class="col-md-14 animate-box text-center" data-animate-effect="fadeInLeft">
                    <h2 class="fh5co-heading">
                        <div class="form-gruop">
                            <a class="btn btn-primary btn-md" href="<?php echo $this->url->getBaseUri(); ?>equip"
                                role="button"> All Equipment </a>
                            <a class="btn btn-primary btn-md" href="<?php echo $this->url->getBaseUri(); ?>equip/add"
                                role="button"> Add Equipment </a>
                        </div>
                    </h2>
                </div>
                <?php } ?>

                <!-- --------------------------------------------------- -->

                <h2 class="fh5co-heading"> Your Total Item : <?php echo $totalItems;?> </h2>


                <div class="col-md-14 animate-box" data-animate-effect="fadeInLeft">
                    <table id="myTable" class="table" style="width:100%">

                            <tr>
                                <?php
            if(!$this->session->has('studentID')){ ?>
                                <th data-field="eqname">Equip ID</th>
                                <?php } ?>
                                <th data-field="eqname">Equip Name</th>
                                <th data-field="eqnum">Quantity</th>
                                <?php
            if(!$this->session->has('studentID')){ ?>
                                <th data-field="eqnum">Lab ID</th>
                                <?php }else{ ?>
                                <th data-field="lendnum">Select Lend Quantity</th>
                                <th data-field="lend"> Lend </th>
                                <?php } ?>

                            </tr>
                        

                        <?php  
              foreach($sentdata as $row){
                  if($row->Lab_id == "405"){  ?>
                        <form action="lendlabmicro" method="post">
                            <tr>
                                <?php if(!$this->session->has('studentID')){ ?>
                                <td>
                                    <p class="fh5co-lead"><?php echo $row->Equip_id ?></p>
                                </td>
                                <?php } ?>
                                <td>
                                    <input type="hidden" id="eqid" name="eqid" value="<?php echo $row->Equip_id?>">
                                    <p class="fh5co-lead"><?php echo $row->Equip_Name ?></p>
                                </td>
                                <td>
                                    <p class="fh5co-lead"><?php if($row->Equip_Num != 0) echo $row->Equip_Num; else echo "Out Of Stock"; ?></p>
                                </td>

                                <?php if(!$this->session->has('studentID')){ ?>
                                <td>
                                    <p class="fh5co-lead"><?php echo $row->Lab_id ?></p>
                                </td>
                                <?php } ?>

                                <?php
            if($this->session->has('studentID')){ ?>
                                <?php if($row->Equip_Num != 0){ ?>
                                <td>
                                    <input type="number" id="eqnum" name="eqnum" class="input-group" value="1" min="1"
                                        max="<?php echo $row->Equip_Num ?>" />
                                <td><input class="btn btn-default center" type="submit" value="LEND"></td>
                                <?php } ?>
                                <?php }else{ ?>
                                <td><a href="<?php echo $this->url->getBaseUri().'equip/edit?eqid='.$row->Equip_id?>">
                                        EDIT
                                    </a></td>

                                <td><a href="<?php echo $this->url->getBaseUri().'equip/delete?eqid='.$row->Equip_id?>">
                                        DELETE </a></td>
                                <?php } ?>
                            </tr>
                        </form>
                        <?php } ?>
                        <?php } ?>

                        <script>
                        $(".bth,.lend").click(function() {
                            var total = parseInt($('#cart').text());
                            var i = $(this).val();
                            $('#cart').text(total);
                            $.ajax({
                                type: "POST",
                                url: "<?php echo $this->url->getBaseUri()?>" + "equip/lend",
                                data: "eqid=" + i,
                                dataType: "html",
                                success: function() {
                                    total = total + 1;
                                    $('#cart').text(total);
                                },
                                error: function() {
                                    alert("problem communicating with the server");
                                }
                            });
                        });
                        </script>


                    </table>
                </div>

            </div>
          
        </div>



    </div>





    </div>

</body>

</html>