<!DOCTYPE html>
<html>
<!-- show list of equipment -->


<head>

    <title>Equipment List</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Marble &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords"
        content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />



    <?php echo $this->getContent(); ?>

</head>


<!-- ------------------------------------------------------------------ -->


<body>
    <div id="fh5co-page">
        <div id="fh5co-main">
            <aside id="fh5co-hero" class="js-fullheight">
                <div class="flexslider js-fullheight">
                    <ul class="slides">
                        <li style="background-image: url(images/bghome.jpg);">
                            <div class="overlay"></div>
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-2 text-center js-fullheight slider-text">
                                        <div class="slider-text-inner">
                                            <h1> <strong> Lab Lender </strong> is a web appilcation that help you see
                                                and
                                                lend all equipments in laboratory</h1>
                                            <h2>Before lending, you should login first or if you don't have an account
                                                click
                                                Sign Up </h2>
                                            <p>
                                                <a class="btn btn-primary btn-demo popup-vimeo"
                                                    href="<?php echo $this->url->getBaseUri(); ?>authen/login"> Sign In
                                                </a>
                                                <a class="btn btn-primary btn-learn"
                                                    href="<?php echo $this->url->getBaseUri(); ?>authen/signup"> Sign Up
                                                </a>
                                                Test
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>

            </aside>
        </div>
    </div>


</body>

</html>